services:
  mysql:
    image: mysql:8
    container_name: gan-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - gan_mysql_data:/var/lib/mysql

volumes:
  gan_mysql_data:
