services:
  db:
    build:
      dockerfile: Dockerfile.mysql.dev
    environment:
      - MYSQL_DATABASE=${WEIGHT_DATABASE}
      - MYSQL_ROOT_PASSWORD=${WEIGHT_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${WEIGHT_ROOT_PASSWORD}"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      dockerfile: Dockerfile.weight.dev
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=${WEIGHT_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${WEIGHT_ROOT_PASSWORD}
    ports:
      - "80:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:

